import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  Plus,
  Trash2,
  Save,
  Edit2,
  Loader2,
  Globe,
  Key,
  Star,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Card } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  api,
  type ProviderApiConfig,
} from "@/lib/api";
import { cn } from "@/lib/utils";
import { Toast, ToastContainer } from "@/components/ui/toast";
import { ModelManager } from "./ModelManager";

interface ProviderApiManagerProps {
  className?: string;
  setToast?: (toast: { message: string; type: 'success' | 'error' } | null) => void;
}

interface EditDialogState {
  open: boolean;
  config: ProviderApiConfig | null;
  isNew: boolean;
}

/**
 * Provider API Manager Component
 * Manages multiple API configurations for each provider
 */
export const ProviderApiManager: React.FC<ProviderApiManagerProps> = ({
  className,
  setToast,
}) => {
  const [configs, setConfigs] = useState<ProviderApiConfig[]>([]);
  const [loading, setLoading] = useState(true);
  const [editDialog, setEditDialog] = useState<EditDialogState>({
    open: false,
    config: null,
    isNew: false,
  });
  const [formData, setFormData] = useState({
    name: "",
    provider_id: "claude",
    base_url: "",
    auth_token: "",
    is_default: false,
  });
  const [saving, setSaving] = useState(false);
  const [localToast, setLocalToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null);

  const showToast = (message: string, type: 'success' | 'error') => {
    if (setToast) {
      setToast({ message, type });
    } else {
      setLocalToast({ message, type });
    }
  };

  useEffect(() => {
    loadConfigs();
  }, []);

  const loadConfigs = async () => {
    try {
      setLoading(true);
      const loadedConfigs = await api.listProviderApiConfigs();
      setConfigs(loadedConfigs);
    } catch (error) {
      console.error("Failed to load provider API configs:", error);
      showToast("Failed to load API configurations", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleCreateNew = () => {
    setFormData({
      name: "",
      provider_id: "claude",
      base_url: "",
      auth_token: "",
      is_default: false,
    });
    setEditDialog({
      open: true,
      config: null,
      isNew: true,
    });
  };

  const handleEdit = (config: ProviderApiConfig) => {
    setFormData({
      name: config.name,
      provider_id: config.provider_id,
      base_url: config.base_url || "",
      auth_token: config.auth_token || "",
      is_default: config.is_default,
    });
    setEditDialog({
      open: true,
      config,
      isNew: false,
    });
  };

  const handleSave = async () => {
    try {
      setSaving(true);

      if (!formData.name.trim()) {
        showToast("Please enter a name", "error");
        return;
      }

      if (editDialog.isNew) {
        // Create new config
        await api.createProviderApiConfig({
          id: "", // Will be generated by backend
          name: formData.name,
          provider_id: formData.provider_id,
          base_url: formData.base_url || undefined,
          auth_token: formData.auth_token || undefined,
          is_default: formData.is_default,
          is_builtin: false,
        });
        showToast("API configuration created successfully", "success");
      } else if (editDialog.config) {
        // Update existing config
        await api.updateProviderApiConfig(editDialog.config.id, {
          name: formData.name,
          base_url: formData.base_url || undefined,
          auth_token: formData.auth_token || undefined,
          is_default: formData.is_default,
        });
        showToast("API configuration updated successfully", "success");
      }

      setEditDialog({ open: false, config: null, isNew: false });
      await loadConfigs();
    } catch (error) {
      console.error("Failed to save config:", error);
      showToast("Failed to save configuration", "error");
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (config: ProviderApiConfig) => {
    if (config.is_builtin) {
      showToast("Cannot delete built-in configuration", "error");
      return;
    }

    // Delete directly without confirmation
    try {
      await api.deleteProviderApiConfig(config.id);
      showToast("Configuration deleted successfully", "success");
      await loadConfigs();
    } catch (error) {
      console.error("Failed to delete config:", error);
      showToast("Failed to delete configuration", "error");
    }
  };

  const handleSetDefault = async (config: ProviderApiConfig) => {
    try {
      await api.updateProviderApiConfig(config.id, {
        is_default: true,
      });
      showToast("Default API configuration updated", "success");
      await loadConfigs();
    } catch (error) {
      console.error("Failed to set default:", error);
      showToast("Failed to update default configuration", "error");
    }
  };

  // Group configs by provider
  const configsByProvider = configs.reduce((acc, config) => {
    if (!acc[config.provider_id]) {
      acc[config.provider_id] = [];
    }
    acc[config.provider_id].push(config);
    return acc;
  }, {} as Record<string, ProviderApiConfig[]>);

  return (
    <div className={cn("space-y-6", className)}>
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-heading-4">Provider API Configurations</h3>
          <p className="text-body-small text-muted-foreground mt-1">
            Manage API endpoints for different providers
          </p>
        </div>
        <Button
          onClick={handleCreateNew}
          size="sm"
          className="gap-2"
        >
          <Plus className="h-4 w-4" />
          Add Configuration
        </Button>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : configs.length === 0 ? (
        <Card className="p-8 text-center">
          <p className="text-body-small text-muted-foreground">
            No API configurations found. Create one to get started.
          </p>
        </Card>
      ) : (
        <div className="space-y-6">
          {Object.entries(configsByProvider).map(([providerId, providerConfigs]) => (
            <div key={providerId} className="space-y-3">
              <h4 className="text-label capitalize">{providerId} API Configurations</h4>
              <div className="grid gap-3">
                {providerConfigs.map((config) => (
                  <motion.div
                    key={config.id}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <Card className={cn(
                      "p-4 hover:border-primary/50 transition-colors",
                      config.is_default && "border-primary"
                    )}>
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex-1 space-y-2">
                          <div className="flex items-center gap-2">
                            <h5 className="text-label font-medium">{config.name}</h5>
                            {config.is_default && (
                              <div className="flex items-center gap-1 px-2 py-0.5 rounded-full bg-primary/10 text-primary text-xs">
                                <Star className="h-3 w-3 fill-current" />
                                Default
                              </div>
                            )}
                            {config.is_builtin && (
                              <div className="px-2 py-0.5 rounded-full bg-muted text-muted-foreground text-xs">
                                Built-in
                              </div>
                            )}
                          </div>

                          {config.base_url && (
                            <div className="flex items-center gap-2 text-caption text-muted-foreground">
                              <Globe className="h-3 w-3" />
                              <span className="font-mono text-xs">{config.base_url}</span>
                            </div>
                          )}

                          {config.auth_token && (
                            <div className="flex items-center gap-2 text-caption text-muted-foreground">
                              <Key className="h-3 w-3" />
                              <span className="font-mono text-xs">
                                {config.auth_token.substring(0, 20)}...
                              </span>
                            </div>
                          )}
                        </div>

                        <div className="flex items-center gap-2">
                          {!config.is_default && (
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => handleSetDefault(config)}
                              className="h-8 px-3 text-xs"
                            >
                              <Star className="h-3 w-3 mr-1" />
                              Set Default
                            </Button>
                          )}
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => handleEdit(config)}
                            className="h-8 w-8"
                          >
                            <Edit2 className="h-4 w-4" />
                          </Button>
                          {!config.is_builtin && (
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleDelete(config)}
                              className="h-8 w-8 hover:text-destructive"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          )}
                        </div>
                      </div>
                    </Card>
                  </motion.div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Edit/Create Dialog */}
      <Dialog open={editDialog.open} onOpenChange={(open) => setEditDialog({ ...editDialog, open })}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>
              {editDialog.isNew ? "Create API Configuration" : "Edit API Configuration"}
            </DialogTitle>
            <DialogDescription>
              Configure API endpoint and authentication details
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name *</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="e.g., Anthropic Official"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="provider">Provider *</Label>
              <select
                id="provider"
                value={formData.provider_id}
                onChange={(e) => setFormData({ ...formData, provider_id: e.target.value })}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                disabled={!editDialog.isNew}
              >
                <option value="claude">Claude</option>
                <option value="openai">OpenAI</option>
                <option value="gemini">Gemini</option>
              </select>
              {!editDialog.isNew && (
                <p className="text-xs text-muted-foreground">
                  Provider cannot be changed after creation
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="base_url">Base URL</Label>
              <Input
                id="base_url"
                value={formData.base_url}
                onChange={(e) => setFormData({ ...formData, base_url: e.target.value })}
                placeholder="https://api.anthropic.com"
                className="font-mono text-sm"
              />
              <p className="text-xs text-muted-foreground">
                Leave empty to use default endpoint
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="auth_token">Authentication Token</Label>
              <Input
                id="auth_token"
                type="password"
                value={formData.auth_token}
                onChange={(e) => setFormData({ ...formData, auth_token: e.target.value })}
                placeholder="sk-ant-..."
                className="font-mono text-sm"
              />
              <p className="text-xs text-muted-foreground">
                Optional: Overrides environment variable
              </p>
            </div>

            <div className="flex items-center justify-between pt-2">
              <div className="space-y-0.5">
                <Label htmlFor="is_default">Set as Default</Label>
                <p className="text-xs text-muted-foreground">
                  Use this configuration by default
                </p>
              </div>
              <Switch
                id="is_default"
                checked={formData.is_default}
                onCheckedChange={(checked) => setFormData({ ...formData, is_default: checked })}
              />
            </div>
          </div>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setEditDialog({ open: false, config: null, isNew: false })}
              disabled={saving}
            >
              Cancel
            </Button>
            <Button
              onClick={handleSave}
              disabled={saving || !formData.name.trim()}
            >
              {saving ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Saving...
                </>
              ) : (
                <>
                  <Save className="mr-2 h-4 w-4" />
                  Save
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Separator */}
      <div className="border-t border-border my-8" />

      {/* Model Configuration Section */}
      <ModelManager setToast={setToast || ((t) => setLocalToast(t))} />

      {/* Toast Notification (if not using parent toast) */}
      {!setToast && (
        <ToastContainer>
          {localToast && (
            <Toast
              message={localToast.message}
              type={localToast.type}
              onDismiss={() => setLocalToast(null)}
            />
          )}
        </ToastContainer>
      )}
    </div>
  );
};
