// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGlobalSshConnection(arg1) {
  return window['go']['main']['App']['AddGlobalSshConnection'](arg1);
}

export function AddProjectToIndex(arg1) {
  return window['go']['main']['App']['AddProjectToIndex'](arg1);
}

export function AddProviderToProject(arg1, arg2) {
  return window['go']['main']['App']['AddProviderToProject'](arg1, arg2);
}

export function CancelAgentRun(arg1) {
  return window['go']['main']['App']['CancelAgentRun'](arg1);
}

export function CancelClaudeExecution(arg1) {
  return window['go']['main']['App']['CancelClaudeExecution'](arg1);
}

export function CancelClaudeExecutionByProject(arg1) {
  return window['go']['main']['App']['CancelClaudeExecutionByProject'](arg1);
}

export function CancelSshSync(arg1) {
  return window['go']['main']['App']['CancelSshSync'](arg1);
}

export function CheckAutoCheckpoint(arg1, arg2) {
  return window['go']['main']['App']['CheckAutoCheckpoint'](arg1, arg2);
}

export function CheckClaudeVersion() {
  return window['go']['main']['App']['CheckClaudeVersion']();
}

export function CheckWorkspaceClean(arg1) {
  return window['go']['main']['App']['CheckWorkspaceClean'](arg1);
}

export function CleanupFinishedProcesses() {
  return window['go']['main']['App']['CleanupFinishedProcesses']();
}

export function CleanupOldCheckpoints(arg1, arg2) {
  return window['go']['main']['App']['CleanupOldCheckpoints'](arg1, arg2);
}

export function CleanupWorkspace(arg1) {
  return window['go']['main']['App']['CleanupWorkspace'](arg1);
}

export function ClearCheckpointManager(arg1, arg2) {
  return window['go']['main']['App']['ClearCheckpointManager'](arg1, arg2);
}

export function CloneRepository(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneRepository'](arg1, arg2, arg3);
}

export function ClosePtySession(arg1) {
  return window['go']['main']['App']['ClosePtySession'](arg1);
}

export function ContinueClaudeCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ContinueClaudeCode'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateCheckpoint(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCheckpoint'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateProviderApiConfig(arg1) {
  return window['go']['main']['App']['CreateProviderApiConfig'](arg1);
}

export function CreatePtySession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreatePtySession'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteAgentRun(arg1) {
  return window['go']['main']['App']['DeleteAgentRun'](arg1);
}

export function DeleteCheckpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteCheckpoint'](arg1, arg2, arg3);
}

export function DeleteClaudeConfigAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteClaudeConfigAgent'](arg1, arg2, arg3);
}

export function DeleteGlobalSshConnection(arg1) {
  return window['go']['main']['App']['DeleteGlobalSshConnection'](arg1);
}

export function DeleteMcpServer(arg1) {
  return window['go']['main']['App']['DeleteMcpServer'](arg1);
}

export function DeleteProjectIndex(arg1) {
  return window['go']['main']['App']['DeleteProjectIndex'](arg1);
}

export function DeleteProviderApiConfig(arg1) {
  return window['go']['main']['App']['DeleteProviderApiConfig'](arg1);
}

export function DeleteSlashCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSlashCommand'](arg1, arg2, arg3);
}

export function DetectWorktree(arg1) {
  return window['go']['main']['App']['DetectWorktree'](arg1);
}

export function ExecuteAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteAgent'](arg1, arg2, arg3, arg4);
}

export function ExecuteClaudeCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteClaudeCode'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteCommandAsync(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteCommandAsync'](arg1, arg2, arg3);
}

export function ExecuteCommandWithArgs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteCommandWithArgs'](arg1, arg2, arg3);
}

export function ExportAgent(arg1) {
  return window['go']['main']['App']['ExportAgent'](arg1);
}

export function ExportAgentToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportAgentToFile'](arg1, arg2);
}

export function FetchGitHubAgentContent(arg1) {
  return window['go']['main']['App']['FetchGitHubAgentContent'](arg1);
}

export function FetchGitHubAgents() {
  return window['go']['main']['App']['FetchGitHubAgents']();
}

export function FindClaudeMdFiles(arg1) {
  return window['go']['main']['App']['FindClaudeMdFiles'](arg1);
}

export function ForkFromCheckpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ForkFromCheckpoint'](arg1, arg2, arg3, arg4);
}

export function GenerateCheckpointID() {
  return window['go']['main']['App']['GenerateCheckpointID']();
}

export function GetActions(arg1, arg2) {
  return window['go']['main']['App']['GetActions'](arg1, arg2);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgentRun(arg1) {
  return window['go']['main']['App']['GetAgentRun'](arg1);
}

export function GetAgentRunBySessionID(arg1) {
  return window['go']['main']['App']['GetAgentRunBySessionID'](arg1);
}

export function GetAgentRunOutput(arg1) {
  return window['go']['main']['App']['GetAgentRunOutput'](arg1);
}

export function GetAllProviderApiConfigs() {
  return window['go']['main']['App']['GetAllProviderApiConfigs']();
}

export function GetAutoSyncStatus(arg1) {
  return window['go']['main']['App']['GetAutoSyncStatus'](arg1);
}

export function GetCheckpointDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCheckpointDiff'](arg1, arg2, arg3, arg4);
}

export function GetCheckpointSettings(arg1, arg2) {
  return window['go']['main']['App']['GetCheckpointSettings'](arg1, arg2);
}

export function GetClaudeBinaryPath() {
  return window['go']['main']['App']['GetClaudeBinaryPath']();
}

export function GetClaudeConfigAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetClaudeConfigAgent'](arg1, arg2, arg3);
}

export function GetClaudeSessionOutput(arg1) {
  return window['go']['main']['App']['GetClaudeSessionOutput'](arg1);
}

export function GetClaudeSettings() {
  return window['go']['main']['App']['GetClaudeSettings']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetGitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitDiff'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetGlobalActions() {
  return window['go']['main']['App']['GetGlobalActions']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetHooks() {
  return window['go']['main']['App']['GetHooks']();
}

export function GetHooksByType(arg1) {
  return window['go']['main']['App']['GetHooksByType'](arg1);
}

export function GetMcpServer(arg1) {
  return window['go']['main']['App']['GetMcpServer'](arg1);
}

export function GetMcpServerStatus(arg1) {
  return window['go']['main']['App']['GetMcpServerStatus'](arg1);
}

export function GetMergedHooksConfig(arg1) {
  return window['go']['main']['App']['GetMergedHooksConfig'](arg1);
}

export function GetPluginAgent(arg1, arg2) {
  return window['go']['main']['App']['GetPluginAgent'](arg1, arg2);
}

export function GetPluginCommand(arg1, arg2) {
  return window['go']['main']['App']['GetPluginCommand'](arg1, arg2);
}

export function GetPluginContents(arg1) {
  return window['go']['main']['App']['GetPluginContents'](arg1);
}

export function GetPluginDetails(arg1) {
  return window['go']['main']['App']['GetPluginDetails'](arg1);
}

export function GetPluginSkill(arg1, arg2) {
  return window['go']['main']['App']['GetPluginSkill'](arg1, arg2);
}

export function GetProjectIndex(arg1) {
  return window['go']['main']['App']['GetProjectIndex'](arg1);
}

export function GetProjectProviderApiConfig(arg1, arg2) {
  return window['go']['main']['App']['GetProjectProviderApiConfig'](arg1, arg2);
}

export function GetProjectSessions(arg1) {
  return window['go']['main']['App']['GetProjectSessions'](arg1);
}

export function GetProviderApiConfig(arg1) {
  return window['go']['main']['App']['GetProviderApiConfig'](arg1);
}

export function GetProviderSystemPrompt(arg1) {
  return window['go']['main']['App']['GetProviderSystemPrompt'](arg1);
}

export function GetSessionMessageIndex(arg1, arg2) {
  return window['go']['main']['App']['GetSessionMessageIndex'](arg1, arg2);
}

export function GetSessionMessagesRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetSessionMessagesRange'](arg1, arg2, arg3, arg4);
}

export function GetSessionStats(arg1, arg2) {
  return window['go']['main']['App']['GetSessionStats'](arg1, arg2);
}

export function GetSessionTimeline(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTimeline'](arg1, arg2);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSlashCommand(arg1, arg2) {
  return window['go']['main']['App']['GetSlashCommand'](arg1, arg2);
}

export function GetSystemPrompt() {
  return window['go']['main']['App']['GetSystemPrompt']();
}

export function GetUnpushedCommitsCount(arg1) {
  return window['go']['main']['App']['GetUnpushedCommitsCount'](arg1);
}

export function GetUnpushedToRemoteCount(arg1) {
  return window['go']['main']['App']['GetUnpushedToRemoteCount'](arg1);
}

export function GetUsageByDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetUsageByDateRange'](arg1, arg2);
}

export function GetUsageDetails(arg1) {
  return window['go']['main']['App']['GetUsageDetails'](arg1);
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function GetWorkspaceProtectionEnabled(arg1) {
  return window['go']['main']['App']['GetWorkspaceProtectionEnabled'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportAgent(arg1) {
  return window['go']['main']['App']['ImportAgent'](arg1);
}

export function ImportAgentFromFile(arg1) {
  return window['go']['main']['App']['ImportAgentFromFile'](arg1);
}

export function ImportAgentFromGitHub(arg1) {
  return window['go']['main']['App']['ImportAgentFromGitHub'](arg1);
}

export function InitLocalGit(arg1, arg2) {
  return window['go']['main']['App']['InitLocalGit'](arg1, arg2);
}

export function IsClaudeSessionRunning(arg1) {
  return window['go']['main']['App']['IsClaudeSessionRunning'](arg1);
}

export function IsClaudeSessionRunningForProject(arg1, arg2) {
  return window['go']['main']['App']['IsClaudeSessionRunningForProject'](arg1, arg2);
}

export function IsFullscreen() {
  return window['go']['main']['App']['IsFullscreen']();
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function IsProcessAlive(arg1) {
  return window['go']['main']['App']['IsProcessAlive'](arg1);
}

export function IsPtySessionAlive(arg1) {
  return window['go']['main']['App']['IsPtySessionAlive'](arg1);
}

export function KillCommand(arg1) {
  return window['go']['main']['App']['KillCommand'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function ListAgentRuns(arg1, arg2) {
  return window['go']['main']['App']['ListAgentRuns'](arg1, arg2);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListCheckpoints(arg1, arg2) {
  return window['go']['main']['App']['ListCheckpoints'](arg1, arg2);
}

export function ListClaudeAgents() {
  return window['go']['main']['App']['ListClaudeAgents']();
}

export function ListClaudeConfigAgents(arg1) {
  return window['go']['main']['App']['ListClaudeConfigAgents'](arg1);
}

export function ListClaudeInstallations() {
  return window['go']['main']['App']['ListClaudeInstallations']();
}

export function ListDirectoryContents(arg1) {
  return window['go']['main']['App']['ListDirectoryContents'](arg1);
}

export function ListGlobalSshConnections() {
  return window['go']['main']['App']['ListGlobalSshConnections']();
}

export function ListInstalledPlugins() {
  return window['go']['main']['App']['ListInstalledPlugins']();
}

export function ListMcpServers() {
  return window['go']['main']['App']['ListMcpServers']();
}

export function ListPluginAgents(arg1) {
  return window['go']['main']['App']['ListPluginAgents'](arg1);
}

export function ListPluginCommands(arg1) {
  return window['go']['main']['App']['ListPluginCommands'](arg1);
}

export function ListPluginHooks(arg1) {
  return window['go']['main']['App']['ListPluginHooks'](arg1);
}

export function ListPluginSkills(arg1) {
  return window['go']['main']['App']['ListPluginSkills'](arg1);
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProviderSessions(arg1, arg2) {
  return window['go']['main']['App']['ListProviderSessions'](arg1, arg2);
}

export function ListPtySessions() {
  return window['go']['main']['App']['ListPtySessions']();
}

export function ListRunningAgentRuns() {
  return window['go']['main']['App']['ListRunningAgentRuns']();
}

export function ListRunningClaudeSessions() {
  return window['go']['main']['App']['ListRunningClaudeSessions']();
}

export function ListSlashCommands(arg1) {
  return window['go']['main']['App']['ListSlashCommands'](arg1);
}

export function LoadAgentSessionHistory(arg1) {
  return window['go']['main']['App']['LoadAgentSessionHistory'](arg1);
}

export function LoadCheckpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadCheckpoint'](arg1, arg2, arg3);
}

export function LoadProviderSessionHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadProviderSessionHistory'](arg1, arg2, arg3);
}

export function LoadSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadSessionHistory'](arg1, arg2);
}

export function McpAdd(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['McpAdd'](arg1, arg2, arg3, arg4, arg5);
}

export function McpAddFromClaudeDesktop(arg1) {
  return window['go']['main']['App']['McpAddFromClaudeDesktop'](arg1);
}

export function McpAddJson(arg1, arg2) {
  return window['go']['main']['App']['McpAddJson'](arg1, arg2);
}

export function McpReadProjectConfig(arg1) {
  return window['go']['main']['App']['McpReadProjectConfig'](arg1);
}

export function McpResetProjectChoices() {
  return window['go']['main']['App']['McpResetProjectChoices']();
}

export function McpSaveProjectConfig(arg1, arg2) {
  return window['go']['main']['App']['McpSaveProjectConfig'](arg1, arg2);
}

export function McpServe() {
  return window['go']['main']['App']['McpServe']();
}

export function McpTestConnection(arg1) {
  return window['go']['main']['App']['McpTestConnection'](arg1);
}

export function NotifyBranchRenamed(arg1, arg2) {
  return window['go']['main']['App']['NotifyBranchRenamed'](arg1, arg2);
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenInExternalApp(arg1, arg2) {
  return window['go']['main']['App']['OpenInExternalApp'](arg1, arg2);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function OpenNewSession(arg1) {
  return window['go']['main']['App']['OpenNewSession'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function PauseSshSync(arg1) {
  return window['go']['main']['App']['PauseSshSync'](arg1);
}

export function PushToMainWorktree(arg1) {
  return window['go']['main']['App']['PushToMainWorktree'](arg1);
}

export function PushToRemote(arg1) {
  return window['go']['main']['App']['PushToRemote'](arg1);
}

export function ReadClaudeMdFile(arg1) {
  return window['go']['main']['App']['ReadClaudeMdFile'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveProjectFromIndex(arg1) {
  return window['go']['main']['App']['RemoveProjectFromIndex'](arg1);
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePty'](arg1, arg2, arg3);
}

export function RestoreCheckpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestoreCheckpoint'](arg1, arg2, arg3, arg4);
}

export function ResumeClaudeCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ResumeClaudeCode'](arg1, arg2, arg3, arg4, arg5);
}

export function ResumeProviderSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ResumeProviderSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResumeSshSync(arg1) {
  return window['go']['main']['App']['ResumeSshSync'](arg1);
}

export function SaveClaudeConfigAgent(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudeConfigAgent'](arg1, arg2);
}

export function SaveClaudeMdFile(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudeMdFile'](arg1, arg2);
}

export function SaveClaudeSettings(arg1) {
  return window['go']['main']['App']['SaveClaudeSettings'](arg1);
}

export function SaveHooks(arg1) {
  return window['go']['main']['App']['SaveHooks'](arg1);
}

export function SaveMcpServer(arg1, arg2) {
  return window['go']['main']['App']['SaveMcpServer'](arg1, arg2);
}

export function SavePastedImage(arg1, arg2) {
  return window['go']['main']['App']['SavePastedImage'](arg1, arg2);
}

export function SaveProjectIndex(arg1) {
  return window['go']['main']['App']['SaveProjectIndex'](arg1);
}

export function SaveProviderApiConfig(arg1) {
  return window['go']['main']['App']['SaveProviderApiConfig'](arg1);
}

export function SaveProviderSystemPrompt(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderSystemPrompt'](arg1, arg2);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SaveSlashCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSlashCommand'](arg1, arg2, arg3, arg4);
}

export function SaveSystemPrompt(arg1) {
  return window['go']['main']['App']['SaveSystemPrompt'](arg1);
}

export function SearchClaudeAgents(arg1) {
  return window['go']['main']['App']['SearchClaudeAgents'](arg1);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SetClaudeBinaryPath(arg1) {
  return window['go']['main']['App']['SetClaudeBinaryPath'](arg1);
}

export function SetProjectProviderApiConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProjectProviderApiConfig'](arg1, arg2, arg3);
}

export function SetWorkspaceProtectionEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspaceProtectionEnabled'](arg1, arg2);
}

export function SkillGet(arg1, arg2) {
  return window['go']['main']['App']['SkillGet'](arg1, arg2);
}

export function SkillsList(arg1) {
  return window['go']['main']['App']['SkillsList'](arg1);
}

export function SpawnProcess(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SpawnProcess'](arg1, arg2, arg3, arg4, arg5);
}

export function StartAutoSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAutoSync'](arg1, arg2, arg3);
}

export function StartProviderSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartProviderSession'](arg1, arg2, arg3, arg4, arg5);
}

export function StopAutoSync(arg1) {
  return window['go']['main']['App']['StopAutoSync'](arg1);
}

export function StorageDeleteRow(arg1, arg2) {
  return window['go']['main']['App']['StorageDeleteRow'](arg1, arg2);
}

export function StorageExecuteSql(arg1) {
  return window['go']['main']['App']['StorageExecuteSql'](arg1);
}

export function StorageInsertRow(arg1, arg2) {
  return window['go']['main']['App']['StorageInsertRow'](arg1, arg2);
}

export function StorageListTables() {
  return window['go']['main']['App']['StorageListTables']();
}

export function StorageReadTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorageReadTable'](arg1, arg2, arg3);
}

export function StorageResetDatabase() {
  return window['go']['main']['App']['StorageResetDatabase']();
}

export function StorageUpdateRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorageUpdateRow'](arg1, arg2, arg3);
}

export function StreamSessionOutput(arg1, arg2) {
  return window['go']['main']['App']['StreamSessionOutput'](arg1, arg2);
}

export function SyncFromSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncFromSSH'](arg1, arg2, arg3);
}

export function SyncToSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncToSSH'](arg1, arg2, arg3);
}

export function TestSshConnection(arg1) {
  return window['go']['main']['App']['TestSshConnection'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function TrackCheckpointMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrackCheckpointMessage'](arg1, arg2, arg3);
}

export function TrackSessionMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrackSessionMessages'](arg1, arg2, arg3);
}

export function UpdateAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateCheckpointSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCheckpointSettings'](arg1, arg2, arg3);
}

export function UpdateGlobalActions(arg1) {
  return window['go']['main']['App']['UpdateGlobalActions'](arg1);
}

export function UpdateProjectAccessTime(arg1) {
  return window['go']['main']['App']['UpdateProjectAccessTime'](arg1);
}

export function UpdateProjectActions(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectActions'](arg1, arg2);
}

export function UpdateProjectFields(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectFields'](arg1, arg2);
}

export function UpdateProjectLastProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectLastProvider'](arg1, arg2);
}

export function UpdateProviderApiConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateProviderApiConfig'](arg1, arg2);
}

export function UpdateProviderSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProviderSession'](arg1, arg2, arg3);
}

export function UpdateWorkspaceActions(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspaceActions'](arg1, arg2);
}

export function UpdateWorkspaceBranch(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspaceBranch'](arg1, arg2);
}

export function UpdateWorkspaceFields(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspaceFields'](arg1, arg2);
}

export function UpdateWorkspaceLastProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspaceLastProvider'](arg1, arg2);
}

export function ValidateHookCommand(arg1) {
  return window['go']['main']['App']['ValidateHookCommand'](arg1);
}

export function WatchGitWorkspace(arg1) {
  return window['go']['main']['App']['WatchGitWorkspace'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteToPty(arg1, arg2) {
  return window['go']['main']['App']['WriteToPty'](arg1, arg2);
}

export function UnwatchGitWorkspace(arg1) {
  return window['go']['main']['App']['UnwatchGitWorkspace'](arg1);
}
