// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ssh} from '../models';
import {main} from '../models';
import {database} from '../models';
import {claude} from '../models';
import {mcp} from '../models';
import {plugin} from '../models';

export function AddGlobalSshConnection(arg1:ssh.SshConnection):Promise<void>;

export function AddProjectToIndex(arg1:string):Promise<void>;

export function AddProviderToProject(arg1:string,arg2:string):Promise<void>;

export function CancelAgentRun(arg1:number):Promise<void>;

export function CancelClaudeExecution(arg1:string):Promise<void>;

export function CancelClaudeExecutionByProject(arg1:string):Promise<void>;

export function CancelSshSync(arg1:string):Promise<void>;

export function CheckClaudeVersion():Promise<main.ClaudeVersionInfo>;

export function CheckWorkspaceClean(arg1:string):Promise<void>;

export function CleanupFinishedProcesses():Promise<Array<string>>;

export function CleanupWorkspace(arg1:string):Promise<string>;

export function CloneRepository(arg1:string,arg2:string,arg3:string):Promise<main.CloneRepositoryResult>;

export function ClosePtySession(arg1:string):Promise<void>;

export function ContinueClaudeCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<number>;

export function CreateModelConfig(arg1:database.ModelConfig):Promise<void>;

export function CreateProject(arg1:string):Promise<void>;

export function CreateProviderApiConfig(arg1:database.ProviderApiConfig):Promise<void>;

export function CreatePtySession(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<main.PtySessionInfo>;

export function CreateWorkspace(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteAgent(arg1:number):Promise<void>;

export function DeleteAgentRun(arg1:number):Promise<void>;

export function DeleteClaudeConfigAgent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteGlobalSshConnection(arg1:string):Promise<void>;

export function DeleteMcpServer(arg1:string):Promise<void>;

export function DeleteModelConfig(arg1:string):Promise<void>;

export function DeleteProjectIndex(arg1:string):Promise<void>;

export function DeleteProviderApiConfig(arg1:string):Promise<void>;

export function DeleteSlashCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DetectWorktree(arg1:string):Promise<main.WorktreeInfo>;

export function ExecuteAgent(arg1:number,arg2:string,arg3:string,arg4:string):Promise<database.AgentRun>;

export function ExecuteClaudeCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ExecuteCommandAsync(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function ExecuteCommandWithArgs(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function ExportAgent(arg1:number):Promise<string>;

export function ExportAgentToFile(arg1:number,arg2:string):Promise<void>;

export function FetchGitHubAgentContent(arg1:string):Promise<any>;

export function FetchGitHubAgents():Promise<Array<any>>;

export function FindClaudeMdFiles(arg1:string):Promise<Array<claude.ClaudeMdFile>>;

export function GetActions(arg1:string,arg2:string):Promise<main.ActionsResult>;

export function GetAgent(arg1:number):Promise<database.Agent>;

export function GetAgentRun(arg1:number):Promise<database.AgentRun>;

export function GetAgentRunBySessionID(arg1:string):Promise<database.AgentRun>;

export function GetAgentRunOutput(arg1:number):Promise<string>;

export function GetAllModelConfigs():Promise<Array<database.ModelConfig>>;

export function GetAllProviderApiConfigs():Promise<Array<database.ProviderApiConfig>>;

export function GetAutoSyncStatus(arg1:string):Promise<ssh.AutoSyncStatus>;

export function GetClaudeBinaryPath():Promise<string>;

export function GetClaudeConfigAgent(arg1:string,arg2:string,arg3:string):Promise<claude.ClaudeAgent>;

export function GetClaudeSessionOutput(arg1:string):Promise<string>;

export function GetClaudeSettings():Promise<Record<string, any>>;

export function GetConfig():Promise<Record<string, string>>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetDefaultModelConfig(arg1:string):Promise<database.ModelConfig>;

export function GetDefaultThinkingLevel(arg1:string):Promise<database.ThinkingLevel>;

export function GetEnabledModelConfigs():Promise<Array<database.ModelConfig>>;

export function GetGitDiff(arg1:string,arg2:boolean):Promise<string>;

export function GetGitStatus(arg1:string):Promise<main.GitRepoStatus>;

export function GetGlobalActions():Promise<Array<main.Action>>;

export function GetHomeDirectory():Promise<string>;

export function GetHooks():Promise<claude.HooksConfig>;

export function GetHooksByType(arg1:string):Promise<Array<claude.HookMatcher>>;

export function GetMcpServer(arg1:string):Promise<mcp.MCPServer>;

export function GetMcpServerStatus(arg1:string):Promise<mcp.MCPServerStatus>;

export function GetMergedHooksConfig(arg1:string):Promise<claude.HooksConfig>;

export function GetModelConfig(arg1:string):Promise<database.ModelConfig>;

export function GetModelConfigByModelID(arg1:string):Promise<database.ModelConfig>;

export function GetModelConfigsByProvider(arg1:string):Promise<Array<database.ModelConfig>>;

export function GetModelThinkingLevels(arg1:string):Promise<Array<database.ThinkingLevel>>;

export function GetPluginAgent(arg1:string,arg2:string):Promise<plugin.PluginAgent>;

export function GetPluginCommand(arg1:string,arg2:string):Promise<plugin.PluginCommand>;

export function GetPluginContents(arg1:string):Promise<plugin.PluginContents>;

export function GetPluginDetails(arg1:string):Promise<plugin.Plugin>;

export function GetPluginSkill(arg1:string,arg2:string):Promise<plugin.PluginSkill>;

export function GetProjectIndex(arg1:string):Promise<database.ProjectIndex>;

export function GetProjectProviderApiConfig(arg1:string,arg2:string):Promise<database.ProviderApiConfig>;

export function GetProjectSessions(arg1:string):Promise<Array<string>>;

export function GetProviderApiConfig(arg1:string):Promise<database.ProviderApiConfig>;

export function GetProviderSystemPrompt(arg1:string):Promise<string>;

export function GetSessionMessageIndex(arg1:string,arg2:string):Promise<Array<number>>;

export function GetSessionMessagesRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<claude.Message>>;

export function GetSessionStats(arg1:string,arg2:string):Promise<Array<any>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSlashCommand(arg1:string,arg2:string):Promise<claude.SlashCommand>;

export function GetSystemPrompt():Promise<string>;

export function GetUnpushedCommitsCount(arg1:string):Promise<number>;

export function GetUnpushedToRemoteCount(arg1:string):Promise<number>;

export function GetUsageByDateRange(arg1:string,arg2:string):Promise<main.UsageStats>;

export function GetUsageDetails(arg1:number):Promise<Array<any>>;

export function GetUsageStats():Promise<main.UsageStats>;

export function Greet(arg1:string):Promise<string>;

export function ImportAgent(arg1:string):Promise<database.Agent>;

export function ImportAgentFromFile(arg1:string):Promise<database.Agent>;

export function ImportAgentFromGitHub(arg1:string):Promise<database.Agent>;

export function InitLocalGit(arg1:string,arg2:boolean):Promise<void>;

export function IsClaudeSessionRunning(arg1:string):Promise<boolean>;

export function IsClaudeSessionRunningForProject(arg1:string,arg2:string):Promise<boolean>;

export function IsFullscreen():Promise<boolean>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function IsProcessAlive(arg1:string):Promise<boolean>;

export function IsPtySessionAlive(arg1:string):Promise<boolean>;

export function KillCommand(arg1:string):Promise<void>;

export function KillProcess(arg1:string):Promise<void>;

export function ListAgentRuns(arg1:number,arg2:number):Promise<Array<database.AgentRun>>;

export function ListAgents():Promise<Array<database.Agent>>;

export function ListClaudeAgents():Promise<Array<main.ClaudeAgentEntry>>;

export function ListClaudeConfigAgents(arg1:string):Promise<Array<claude.ClaudeAgent>>;

export function ListClaudeInstallations():Promise<Array<main.ClaudeInstallation>>;

export function ListDirectoryContents(arg1:string):Promise<Array<main.FileEntry>>;

export function ListGlobalSshConnections():Promise<Array<ssh.SshConnection>>;

export function ListInstalledPlugins():Promise<Array<plugin.Plugin>>;

export function ListMcpServers():Promise<Array<mcp.MCPServer>>;

export function ListPluginAgents(arg1:string):Promise<Array<plugin.PluginAgent>>;

export function ListPluginCommands(arg1:string):Promise<Array<plugin.PluginCommand>>;

export function ListPluginHooks(arg1:string):Promise<Array<plugin.PluginHook>>;

export function ListPluginSkills(arg1:string):Promise<Array<plugin.PluginSkill>>;

export function ListProcesses():Promise<Array<string>>;

export function ListProjects():Promise<Array<database.ProjectIndex>>;

export function ListProviderSessions(arg1:string,arg2:string):Promise<Array<main.ProviderSession>>;

export function ListPtySessions():Promise<Array<string>>;

export function ListRunningAgentRuns():Promise<Array<database.AgentRun>>;

export function ListRunningClaudeSessions():Promise<Array<claude.SessionStatus>>;

export function ListSlashCommands(arg1:string):Promise<Array<claude.SlashCommand>>;

export function LoadAgentSessionHistory(arg1:string):Promise<Array<claude.Message>>;

export function LoadProviderSessionHistory(arg1:string,arg2:string,arg3:string):Promise<Array<claude.Message>>;

export function LoadSessionHistory(arg1:string,arg2:string):Promise<Array<claude.Message>>;

export function McpAdd(arg1:string,arg2:string,arg3:Array<string>,arg4:Record<string, string>,arg5:string):Promise<main.MCPAddResult>;

export function McpAddFromClaudeDesktop(arg1:string):Promise<main.MCPImportResult>;

export function McpAddJson(arg1:string,arg2:string):Promise<main.MCPAddResult>;

export function McpReadProjectConfig(arg1:string):Promise<main.MCPProjectConfig>;

export function McpResetProjectChoices():Promise<string>;

export function McpSaveProjectConfig(arg1:string,arg2:main.MCPProjectConfig):Promise<string>;

export function McpServe():Promise<string>;

export function McpTestConnection(arg1:string):Promise<string>;

export function NotifyBranchRenamed(arg1:string,arg2:string):Promise<void>;

export function OpenDirectoryDialog(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<string>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenInExternalApp(arg1:string,arg2:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function OpenNewSession(arg1:string):Promise<string>;

export function OpenUrl(arg1:string):Promise<void>;

export function PauseSshSync(arg1:string):Promise<void>;

export function PushToMainWorktree(arg1:string):Promise<string>;

export function PushToRemote(arg1:string):Promise<string>;

export function ReadClaudeMdFile(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveProjectFromIndex(arg1:string):Promise<void>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function ResizePty(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResumeClaudeCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ResumeProviderSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function ResumeSshSync(arg1:string):Promise<void>;

export function SaveClaudeConfigAgent(arg1:claude.ClaudeAgent,arg2:string):Promise<void>;

export function SaveClaudeMdFile(arg1:string,arg2:string):Promise<void>;

export function SaveClaudeSettings(arg1:Record<string, any>):Promise<void>;

export function SaveHooks(arg1:claude.HooksConfig):Promise<void>;

export function SaveMcpServer(arg1:string,arg2:mcp.MCPServerConfig):Promise<void>;

export function SavePastedImage(arg1:string,arg2:string):Promise<string>;

export function SaveProjectIndex(arg1:database.ProjectIndex):Promise<void>;

export function SaveProviderApiConfig(arg1:database.ProviderApiConfig):Promise<void>;

export function SaveProviderSystemPrompt(arg1:string,arg2:string):Promise<string>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SaveSlashCommand(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveSystemPrompt(arg1:string):Promise<void>;

export function SearchClaudeAgents(arg1:string):Promise<Array<main.ClaudeAgentEntry>>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<main.FileEntry>>;

export function SetClaudeBinaryPath(arg1:string):Promise<void>;

export function SetModelConfigDefault(arg1:string):Promise<void>;

export function SetModelConfigEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetProjectProviderApiConfig(arg1:string,arg2:string,arg3:database.ProviderApiConfig):Promise<void>;

export function SkillGet(arg1:string,arg2:string):Promise<main.Skill>;

export function SkillsList(arg1:string):Promise<Array<main.Skill>>;

export function SpawnProcess(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:Array<string>):Promise<main.ProcessInfo>;

export function StartAutoSync(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartProviderSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function StopAutoSync(arg1:string):Promise<void>;

export function StorageDeleteRow(arg1:string,arg2:number):Promise<void>;

export function StorageExecuteSql(arg1:string):Promise<database.TableData>;

export function StorageInsertRow(arg1:string,arg2:Record<string, any>):Promise<number>;

export function StorageListTables():Promise<Array<string>>;

export function StorageReadTable(arg1:string,arg2:number,arg3:number):Promise<database.TableData>;

export function StorageResetDatabase():Promise<void>;

export function StorageUpdateRow(arg1:string,arg2:number,arg3:Record<string, any>):Promise<void>;

export function StreamSessionOutput(arg1:string,arg2:string):Promise<void>;

export function SyncFromSSH(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncToSSH(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestSshConnection(arg1:ssh.SshConnection):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function UnwatchGitWorkspace(arg1:string):Promise<void>;

export function UpdateAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function UpdateGlobalActions(arg1:Array<main.Action>):Promise<void>;

export function UpdateModelConfig(arg1:string,arg2:database.ModelConfig):Promise<void>;

export function UpdateProjectAccessTime(arg1:string):Promise<void>;

export function UpdateProjectActions(arg1:string,arg2:Array<main.Action>):Promise<void>;

export function UpdateProjectFields(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateProjectLastProvider(arg1:string,arg2:string):Promise<void>;

export function UpdateProviderApiConfig(arg1:string,arg2:Record<string, any>):Promise<database.ProviderApiConfig>;

export function UpdateProviderSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateWorkspaceActions(arg1:string,arg2:Array<main.Action>):Promise<void>;

export function UpdateWorkspaceBranch(arg1:string,arg2:string):Promise<void>;

export function UpdateWorkspaceFields(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateWorkspaceLastProvider(arg1:string,arg2:string):Promise<void>;

export function ValidateHookCommand(arg1:string):Promise<main.HookValidationResult>;

export function WatchGitWorkspace(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteToPty(arg1:string,arg2:string):Promise<void>;
